//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612019
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int ID { get; set; }
        public Nullable<int> GioHang_STT { get; set; }
        public string KhachHang_CMND { get; set; }
        public Nullable<int> MaKhuyenMai_ID { get; set; }
        public Nullable<int> LoaiThanhDon { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<decimal> TongGiaTriNhap { get; set; }
        public Nullable<decimal> TongGiaTriBan { get; set; }
        public Nullable<decimal> TienConLaiPhaiTra { get; set; }
    
        public virtual GioHang GioHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MaKhuyenMai MaKhuyenMai { get; set; }
    }
}
