//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612019
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LoaiSanPham_ID { get; set; }
        public byte[] HinhAnh { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string Model { get; set; }
        public string CPU { get; set; }
        public string Ram { get; set; }
        public string OCung { get; set; }
        public string CDDVD { get; set; }
        public string CardVGA { get; set; }
        public string ManHinh { get; set; }
        public string KetNoi { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public string Pin { get; set; }
        public string HeDieuHanh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> HienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
